import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import styles from './page.module.css'
const inter = Inter({ subsets: ['latin'] })
export default function ProgramB()
{
   return (
        <div className={styles.container}>
            <Head> 
                <title> Program B </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
      <main className={styles.main}>
      <h1> Program B:   </h1>
    <p> Life Skills Essentials Program is tailored towards people with more involved needs that 
        benefit better in a life skills specific program to help them function out into the community. </p>
    <p> In this program, we will have different courses that will modify the life skills program in a way where our more impacted individuals can understand.</p>
<p> Our courses and curriculum in this program will include: Life Skills 1, and Life Skills 2, beginning and intermediate respectively.</p>
<h2> Life Skills I </h2>
  <h5>Unit 1:   Job/Career Tips I</h5>
  <ul>
        <li> Resume basics: how to structure your resume, category location, etc </li>
        <li>Cover Letter basics: how to structure your cover letter</li>
        <li>career assessments  </li>
  </ul>
  <h5> Unit 2:  Medical Basics I </h5>
  <ul>
        <li> health and hygene review (brushing your teeth, getting ready for work, etc)  </li>
        <li> how to schedule and find a doctor   </li>
  </ul>
  <h5>Unit 3: Driving and Transportation tips</h5>
  <ul>
        <li> permit tips </li>
        <li>license tips </li>
        <li>how to get a bus, or train pass (if a driver license is too hard) </li>
        <li> how to read a schedule  </li>
  </ul>
  <h5>Unit 4: Cleaning</h5>
  <ul>
            <li> how to get some cleaning supplies </li>
            <li>how to do laundry: darks   </li>
            <li> how to do laundry: colors </li>
            <li> how to make your bed </li>
            <li> how to clean your room </li>
            <li> how to clean your bathroom </li>
            <li> how to clean your kitchen </li>
      </ul>
  <h5>Unit 5: Shopping and Budgeting</h5>
  <ul>
        <li> how to write a grocery list </li>
        <li>nutrition basics </li>
        <li> different types of shopping and tips for each   </li>
        <li> importance of healthy food  </li>
        <li>how to write a clothes list </li>
        <li> how to check to see what clothes fit you </li>
  </ul>
  <h5>Unit 6: Cooking Basics</h5>
  <ul>
        <li> instruction terminology </li>
        <li> measurements </li>
        <li>nutrition basics  </li>
        <li>tools and what they mean </li>
        <li> how to read a recipe </li>
        <li> how to use a microwave </li>
        <li> how to use a stove </li>
  </ul>
  <h4>Life Skills 102: LIFE 102: Life Skills II </h4>
  <h5>Unit 1:   Job/Career Tips II</h5>
  <ul>
      <li> interview prep skills and tips </li>
      <li> how to dress for an interview </li>
      <li> how to write a thank you letter </li>
      <li> how to write a follow up letter </li>
      <li> how to write a cover letter </li>
  </ul>
      <h5> Unit 2:  Medical Basics II </h5>
      <ul>
              <li> how to schedule and find a doctor </li>
                  <li> how to find a dentist </li>
                  <li> basics of health insurance  </li>
                  <li> how to fill a perscrpition </li>
                  <li> how to find a pharmacy </li>
                  </ul>
      <h5>Unit 3: Cleaning Baiscs II</h5>
      <ul>
                  <li> how to change your sheets </li>
                  <li> how to do laundry: whites </li>
                  <li> how to do laundry: delicates </li>
                  <li> how to do laundry: towels </li>
                  <li> essential areas where cleaning is needed (overview)</li>
      </ul>
      <h5>Unit 4: Nutrition Basics</h5>
      <ul>
                  <li> how to read a nutrition label </li>
                  <li> the food pyramid </li>
                  <li> processed food vs natural food</li>
                  </ul>

      <h5>Unit 5: Cooking Basics II: safety and food handlers</h5>
  <ul>
        <li> how to get a license </li>
        <li> hygene essentials  </li>
        <li> how to properly use and maintain kitchen tools</li>
        <li> different types of foodbourne illnesses and how to prevent them</li>
        <li> how to properly use and maintain silverwear</li>
        <li> food temperatures  (meats, dairy, etc)</li>
  </ul>
    <p>To learn about Program A, click on the link below:</p>

</main> 
</div>
   )}