"use client"
import NextLink from 'next/link';
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { VStack, Button } from '@chakra-ui/react'
import { Inter } from 'next/font/google'
import styles from './page.module.css'
const inter = Inter({ subsets: ['latin'] })
export default function ProgramB() {
  return (
    <main className={styles.container}>
      <Head>
        <title> Program B </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1> Program B: Life Skills Essentials Program </h1>
      <p>
        Life Skills Essentials Program is tailored towards people with more involved needs that benefit better in a life
        skills specific program to help them function out into the community.
      </p>
      <p>
        In this program, we will have different courses that will modify the life skills program in a way where our more
        impacted individuals can understand.
      </p>
      <p> Our courses and curriculum in this program will include: Life Skills 1, and Life Skills 2, beginning and intermediate respectively.</p>
      <h4 className={styles.header}>  Life Skills I</h4>
      <h4 className={styles.header}> Life Skills II</h4>
      <p>To learn about Program A, click on the Program A button below, or on the header above.</p>
      <VStack className={styles.vstack} padding="10">
        <NextLink href="/ProgramA" passHref>
          <Button as="a" backgroundColor="brand.100">  Program A</Button>
        </NextLink>
      </VStack>
    </main>
  );
}