"use client"
import { useRouter } from 'next/navigation';
import {useState} from 'react'
import styles from './page.module.css'

const validateEmail = (email) => {
  const re = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-1]\d{1,2}\.[0-1]\d{1,2}\.[0-1]\d{1,2}\.[0-1]\d{1,2}\])|(([a-zA-Z]+\.)+[a-zA-Z]{2,}))$/;
  return re.test(String(email).toLowerCase());
}

const validateName = (name) => {
  const re = /^[A-Z][a-z]+(\s|,)[A-Z][a-z]{1,19}$/;
  return re.test(String(name));
}

const validatePhoneNumber = (phoneNumber) => {
  const re = /^\d{10}$/;
  return re.test(String(phoneNumber));
}

const validateAddress = (address) => {
  const re = /^[0-9a-zA-Z\s,.'-]{3,}$/;
  return re.test(String(address));
}

const validateCity = (city) => {
  const re = /^[a-zA-Z\s,.'-]{3,}$/;
  return re.test(String(city));
}

const validateZipCode = (zipCode) => {
  const re = /^\d{5}$/;
  return re.test(String(zipCode));
}

const validateDateOfBirth = (dateOfBirth) => {
  const re = /^\d{4}-\d{2}-\d{2}$/;
  return re.test(String(dateOfBirth));
}

export default function SignUp() {
  const [email, setEmail] = useState("");
  const [name, setName] = useState("");
  const [phoneNumber, setPhoneNumber] = useState("");
  const [address, setAddress] = useState("");
  const [city, setCity] = useState("");
  const [state, setState] = useState("");
  const [zipCode, setZipCode] = useState("");
  const [dateOfBirth, setDateOfBirth] = useState("");
  const router = useRouter();

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!validateEmail(email) && !validateName(name) && !validatePhoneNumber(phoneNumber) && !validateAddress(address) && !validateCity(city) && !validateZipCode(zipCode)) {
      alert("Error: form not accurate.");
    } else if (!validateName(name)) {
      alert("Please enter a valid name. It must be two names.");
    } else if (!validateEmail(email)) {
      alert("Please enter a valid email");
    } else if (!validatePhoneNumber(phoneNumber)) {
      alert("Please enter a valid phone number");
    } else if (!validateAddress(address)) {
      alert("Please enter a valid address");
    } else if (!validateCity(city)) {
      alert("Please enter a valid city");
    } else if (!validateZipCode(zipCode)) {
      alert("Please enter a valid zip code");
    } else if (!validateDateOfBirth(dateOfBirth)) {
      alert("Please enter a valid date of birth");
    } else {
      setEmail("");
      setName("");
      setPhoneNumber("");
      setAddress("");
      setCity("");
      setState("");
      setZipCode("");
      setDateOfBirth("");
      alert("Thank you for signing up!");
      router.push('/success');
    }
  }

  return (
    <div className={styles.main}>
      <Head>
        <title>Sign Up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Sign Up
        </h1>
        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <label htmlFor="name">Full Name</label>
            <input type="text" className="form-control" id="name" placeholder="Enter full name" required value={name} onChange={(e) => setName(e.target.value)} />
          </div>
          <div className="form-group">
            <label htmlFor="email">Email</label>
            <input type="email" className="form-control" id="email" placeholder="Enter email" required value={email} onChange={(e) => setEmail(e.target.value)} />
          </div>
          <div className="form-group">
            <label htmlFor="phoneNumber">Phone Number</label>
            <input type="tel" className="form-control" id="phoneNumber" placeholder="Enter phone number" required value={phoneNumber} onChange={(e) => setPhoneNumber(e.target.value)} />
          </div>
          <div className="form-group">
            <label htmlFor="address">Address</label>
            <input type="text" className="form-control" id="address" placeholder="Enter address" required value={address} onChange={(e) => setAddress(e.target.value)} />
          </div>
          <div className="form-group">
            <label htmlFor="city">City</label>
            <input type="text" className="form-control" id="city" placeholder="Enter city" required value={city} onChange={(e) => setCity(e.target.value)} />
          </div>
          <div className="form-group">
            <label htmlFor="state">State (select below)</label>
            <select className="form-control" id="state" value={state} onChange={(e) => setState(e.target.value)}>
              <option value="AL">Alabama</option>
              <option value="AK">Alaska</option>
              <option value="AZ">Arizona</option>
              <option value="AR">Arkansas</option>
              <option value="CA">California</option>
              <option value="CO">Colorado</option>
              <option value="CT">Connecticut</option>
              <option value="DE">Delaware</option>
              <option value="DC">District Of Columbia</option>
              <option value="FL">Florida</option>
              <option value="GA">Georgia</option>
              <option value="HI">Hawaii</option>
              <option value="ID">Idaho</option>
              <option value="IL">Illinois</option>
              <option value="IN">Indiana</option>
              <option value="IA">Iowa</option>
              <option value="KS">Kansas</option>
              <option value="KY">Kentucky</option>
              <option value="LA">Louisiana</option>
              <option value="ME">Maine</option>
              <option value="MD">Maryland</option>
              <option value="MA">Massachusetts</option>
              <option value="MI">Michigan</option>
              <option value="MN">Minnesota</option>
              <option value="MS">Mississippi</option>
              <option value="MO">Missouri</option>
              <option value="MT">Montana</option>
              <option value="NE">Nebraska</option>
              <option value="NV">Nevada</option>
              <option value="NH">New Hampshire</option>
              <option value="NJ">New Jersey</option>
              <option value="NM">New Mexico</option>
              <option value="NY">New York</option>
              <option value="NC">North Carolina</option>
              <option value="ND">North Dakota</option>
              <option value="OH">Ohio</option>
              <option value="OK">Oklahoma</option>
              <option value="OR">Oregon</option>
              <option value="PA">Pennsylvania</option>
              <option value="RI">Rhode Island</option>
              <option value="SC">South Carolina</option>
              <option value="SD">South Dakota</option>
              <option value="TN">Tennessee</option>
              <option value="TX">Texas</option>
              <option value="UT">Utah</option>
              <option value="VT">Vermont</option>
              <option value="VA">Virginia</option>
              <option value="WA">Washington</option>
              <option value="WV">West Virginia</option>
              <option value="WI">Wisconsin</option>
              <option value="WY">Wyoming</option>
            </select>
          </div>
          <div className="form-group">
            <label htmlFor="zipCode">Zip Code</label>
            <input type="text" className="form-control" id="zipCode" placeholder="Enter zip code" required value={zipCode} onChange={(e) => setZipCode(e.target.value)} />
          </div>
          <div className="form-group">
            <label htmlFor="dateOfBirth">Date of Birth</label>
            <input type="date" className="form-control" id="dateOfBirth" min="1923-01-02" max="2023-05-22" placeholder="Enter date of birth" required value={dateOfBirth} onChange={(e) => setDateOfBirth(e.target.value)} />
          </div>
          <button type="submit">Submit</button>
        </form>
      </main>
      <Link href="/"> </Link>
    </div>
  )
}
